name: PHP Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phplint:
    name: Run PHP Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Run PHP Linter
      run: |
        find . -name "*.php" -print0 | xargs -0 -n 1 php -l
